version: "3.5"

x-template: &template
  tty: true
  stdin_open: true
  build: .

services:
  master:
    <<: *template
    ports: [ "2200:22" ]

  worker-1:
    <<: *template
    ports: [ "2201:22" ]

  worker-2:
    <<: *template
    ports: [ "2202:22" ]
